# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: 'Default'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/test-output/junitreports/TEST-*.xml'
    goals: 'package'

schedules:
- cron: "0 2 * * Mon-Fri"
  displayName: SOI Daily Mid Night build
- cron: "0 14 * * Mon-Fri"
  displayName: SOI Daily Mid Day build
  
